.PHONY: setup-dev setup-staging setup-deploy help

DEV_CONFIG := .dev-config
STAGING_CONFIG := .staging-config
DEPLOY_CONFIG := .deploy-config

# Default values (can be overridden via command line or environment)
AI_PROVIDER ?=
AI_API_KEY ?=
AI_URL ?=
CLOUD_PROVIDER ?=
POSTGRES_PASSWORD ?=
DB_MIGRATION_USER ?= migration
DB_MIGRATION_PASSWORD ?=
DB_APP_USER ?= appuser
DB_APP_PASSWORD ?=
DB_KEYCLOAK_USER ?= keycloak
DB_KEYCLOAK_PASSWORD ?=
KEYCLOAK_ADMIN ?=
KEYCLOAK_ADMIN_PASSWORD ?=

help:
	@echo "Available commands:"
	@echo "  make setup-dev     - Configure local development environment"
	@echo "  make setup-staging - Configure staging environment (cloud)"
	@echo "  make setup-deploy  - Configure production environment (cloud)"
	@echo "  make test-setup    - Run automated tests for setup commands"
	@echo "  make help          - Show this help message"
	@echo ""
	@echo "Non-interactive mode (example):"
	@echo "  make setup-dev AI_PROVIDER=openai AI_API_KEY=sk-xxx"

# ============================================================
# SETUP DEV - Local Docker, default credentials
# ============================================================
setup-dev:
	@if [ -z "$(AI_PROVIDER)" ]; then \
		echo "╔════════════════════════════════════════╗"; \
		echo "║      Development Setup (Local)         ║"; \
		echo "╚════════════════════════════════════════╝"; \
		echo ""; \
		echo "┌─ AI Provider ──────────────────────────────"; \
		echo "│  1) OpenAI"; \
		echo "│  2) Gemini (Google)"; \
		echo "│  3) Anthropic"; \
		echo "│  4) Mistral"; \
		echo "│  5) Ollama (local)"; \
		echo "│  6) LM Studio (local)"; \
		echo "└──────────────────────────────────────────"; \
		read -p "Enter choice [1-6]: " ai_choice; \
		case $$ai_choice in \
			1) ai_provider="openai"; ai_key_name="OPENAI_API_KEY";; \
			2) ai_provider="gemini"; ai_key_name="GOOGLE_API_KEY";; \
			3) ai_provider="anthropic"; ai_key_name="ANTHROPIC_API_KEY";; \
			4) ai_provider="mistral"; ai_key_name="MISTRAL_API_KEY";; \
			5) ai_provider="ollama"; ai_key_name="";; \
			6) ai_provider="lmstudio"; ai_key_name="";; \
			*) echo "Invalid choice"; exit 1;; \
		esac; \
		ai_api_key=""; \
		ai_url=""; \
		if [ -n "$$ai_key_name" ]; then \
			echo ""; \
			read -s -p "Enter $$ai_key_name: " ai_api_key; \
			echo ""; \
		else \
			if [ "$$ai_provider" = "ollama" ]; then \
				default_url="http://localhost:11434"; \
			else \
				default_url="http://localhost:1234"; \
			fi; \
			echo ""; \
			read -p "Enter $$ai_provider URL [$$default_url]: " ai_url; \
			ai_url=$${ai_url:-$$default_url}; \
		fi; \
	else \
		ai_provider="$(AI_PROVIDER)"; \
		ai_api_key="$(AI_API_KEY)"; \
		ai_url="$(AI_URL)"; \
		case $$ai_provider in \
			openai) ai_key_name="OPENAI_API_KEY";; \
			gemini) ai_key_name="GOOGLE_API_KEY";; \
			anthropic) ai_key_name="ANTHROPIC_API_KEY";; \
			mistral) ai_key_name="MISTRAL_API_KEY";; \
			ollama|lmstudio) ai_key_name="";; \
			*) echo "[FAIL] Invalid AI_PROVIDER: $$ai_provider"; exit 1;; \
		esac; \
		if [ -z "$$ai_key_name" ] && [ -z "$$ai_url" ]; then \
			if [ "$$ai_provider" = "ollama" ]; then \
				ai_url="http://localhost:11434"; \
			else \
				ai_url="http://localhost:1234"; \
			fi; \
		fi; \
	fi; \
	\
	echo "# Auto-generated by make setup-dev" > $(DEV_CONFIG); \
	echo "" >> $(DEV_CONFIG); \
	echo "# Environment" >> $(DEV_CONFIG); \
	echo "ENVIRONMENT=dev" >> $(DEV_CONFIG); \
	echo "" >> $(DEV_CONFIG); \
	echo "# AI Provider" >> $(DEV_CONFIG); \
	echo "AI_PROVIDER=$$ai_provider" >> $(DEV_CONFIG); \
	if [ -n "$$ai_key_name" ] && [ -n "$$ai_api_key" ]; then \
		echo "$$ai_key_name=$$ai_api_key" >> $(DEV_CONFIG); \
	fi; \
	if [ -n "$$ai_url" ]; then \
		echo "AI_URL=$$ai_url" >> $(DEV_CONFIG); \
	fi; \
	echo "" >> $(DEV_CONFIG); \
	echo "# PostgreSQL" >> $(DEV_CONFIG); \
	echo "POSTGRES_PASSWORD=postgres" >> $(DEV_CONFIG); \
	echo "" >> $(DEV_CONFIG); \
	echo "# Migration User" >> $(DEV_CONFIG); \
	echo "DB_MIGRATION_USER=migration" >> $(DEV_CONFIG); \
	echo "DB_MIGRATION_PASSWORD=migration" >> $(DEV_CONFIG); \
	echo "" >> $(DEV_CONFIG); \
	echo "# Application User" >> $(DEV_CONFIG); \
	echo "DB_APP_USER=appuser" >> $(DEV_CONFIG); \
	echo "DB_APP_PASSWORD=appuser" >> $(DEV_CONFIG); \
	echo "" >> $(DEV_CONFIG); \
	echo "# Keycloak Database User" >> $(DEV_CONFIG); \
	echo "DB_KEYCLOAK_USER=keycloak" >> $(DEV_CONFIG); \
	echo "DB_KEYCLOAK_PASSWORD=keycloak" >> $(DEV_CONFIG); \
	echo "" >> $(DEV_CONFIG); \
	echo "# Keycloak Admin" >> $(DEV_CONFIG); \
	echo "KEYCLOAK_ADMIN=admin" >> $(DEV_CONFIG); \
	echo "KEYCLOAK_ADMIN_PASSWORD=admin" >> $(DEV_CONFIG); \
	echo "" >> $(DEV_CONFIG); \
	echo "# Keycloak Test User" >> $(DEV_CONFIG); \
	echo "KEYCLOAK_TEST_USER=testuser" >> $(DEV_CONFIG); \
	echo "KEYCLOAK_TEST_PASSWORD=testuser" >> $(DEV_CONFIG); \
	\
	echo ""; \
	echo "[OK] Dev config saved to $(DEV_CONFIG)"

# ============================================================
# SETUP STAGING - Cloud VM, default credentials
# ============================================================
setup-staging:
	@if [ -z "$(CLOUD_PROVIDER)" ] || [ -z "$(AI_PROVIDER)" ]; then \
		echo "╔════════════════════════════════════════╗"; \
		echo "║       Staging Setup (Cloud)            ║"; \
		echo "╚════════════════════════════════════════╝"; \
		echo ""; \
		if [ -z "$(CLOUD_PROVIDER)" ]; then \
			echo "┌─ Cloud Provider ─────────────────────────"; \
			echo "│  1) AWS"; \
			echo "│  2) GCP"; \
			echo "│  3) Azure"; \
			echo "└──────────────────────────────────────────"; \
			read -p "Enter choice [1-3]: " cloud_choice; \
			case $$cloud_choice in \
				1) provider="aws";; \
				2) provider="gcp";; \
				3) provider="azure";; \
				*) echo "[FAIL] Invalid choice"; exit 1;; \
			esac; \
		else \
			provider="$(CLOUD_PROVIDER)"; \
		fi; \
		echo ""; \
		if [ -z "$(AI_PROVIDER)" ]; then \
			echo "┌─ AI Provider ──────────────────────────────"; \
			echo "│  1) OpenAI"; \
			echo "│  2) Gemini (Google)"; \
			echo "│  3) Anthropic"; \
			echo "│  4) Mistral"; \
			echo "│  5) Ollama (local)"; \
			echo "│  6) LM Studio (local)"; \
			echo "└──────────────────────────────────────────"; \
			read -p "Enter choice [1-6]: " ai_choice; \
			case $$ai_choice in \
				1) ai_provider="openai"; ai_key_name="OPENAI_API_KEY";; \
				2) ai_provider="gemini"; ai_key_name="GOOGLE_API_KEY";; \
				3) ai_provider="anthropic"; ai_key_name="ANTHROPIC_API_KEY";; \
				4) ai_provider="mistral"; ai_key_name="MISTRAL_API_KEY";; \
				5) ai_provider="ollama"; ai_key_name="";; \
				6) ai_provider="lmstudio"; ai_key_name="";; \
				*) echo "[FAIL] Invalid choice"; exit 1;; \
			esac; \
			ai_api_key=""; \
			ai_url=""; \
			if [ -n "$$ai_key_name" ]; then \
				echo ""; \
				read -s -p "Enter $$ai_key_name: " ai_api_key; \
				echo ""; \
			else \
				if [ "$$ai_provider" = "ollama" ]; then \
					default_url="http://localhost:11434"; \
				else \
					default_url="http://localhost:1234"; \
				fi; \
				echo ""; \
				read -p "Enter $$ai_provider URL [$$default_url]: " ai_url; \
				ai_url=$${ai_url:-$$default_url}; \
			fi; \
		else \
			ai_provider="$(AI_PROVIDER)"; \
			ai_api_key="$(AI_API_KEY)"; \
			ai_url="$(AI_URL)"; \
			case $$ai_provider in \
				openai) ai_key_name="OPENAI_API_KEY";; \
				gemini) ai_key_name="GOOGLE_API_KEY";; \
				anthropic) ai_key_name="ANTHROPIC_API_KEY";; \
				mistral) ai_key_name="MISTRAL_API_KEY";; \
				ollama|lmstudio) ai_key_name="";; \
				*) echo "[FAIL] Invalid AI_PROVIDER: $$ai_provider"; exit 1;; \
			esac; \
			if [ -z "$$ai_key_name" ] && [ -z "$$ai_url" ]; then \
				if [ "$$ai_provider" = "ollama" ]; then \
					ai_url="http://localhost:11434"; \
				else \
					ai_url="http://localhost:1234"; \
				fi; \
			fi; \
		fi; \
	else \
		provider="$(CLOUD_PROVIDER)"; \
		ai_provider="$(AI_PROVIDER)"; \
		ai_api_key="$(AI_API_KEY)"; \
		ai_url="$(AI_URL)"; \
		case $$ai_provider in \
			openai) ai_key_name="OPENAI_API_KEY";; \
			gemini) ai_key_name="GOOGLE_API_KEY";; \
			anthropic) ai_key_name="ANTHROPIC_API_KEY";; \
			mistral) ai_key_name="MISTRAL_API_KEY";; \
			ollama|lmstudio) ai_key_name="";; \
			*) echo "[FAIL] Invalid AI_PROVIDER: $$ai_provider"; exit 1;; \
		esac; \
		if [ -z "$$ai_key_name" ] && [ -z "$$ai_url" ]; then \
			if [ "$$ai_provider" = "ollama" ]; then \
				ai_url="http://localhost:11434"; \
			else \
				ai_url="http://localhost:1234"; \
			fi; \
		fi; \
	fi; \
	\
	echo "# Auto-generated by make setup-staging" > $(STAGING_CONFIG); \
	echo "" >> $(STAGING_CONFIG); \
	echo "# Cloud & Environment" >> $(STAGING_CONFIG); \
	echo "CLOUD_PROVIDER=$$provider" >> $(STAGING_CONFIG); \
	echo "ENVIRONMENT=staging" >> $(STAGING_CONFIG); \
	echo "" >> $(STAGING_CONFIG); \
	echo "# AI Provider" >> $(STAGING_CONFIG); \
	echo "AI_PROVIDER=$$ai_provider" >> $(STAGING_CONFIG); \
	if [ -n "$$ai_key_name" ] && [ -n "$$ai_api_key" ]; then \
		echo "$$ai_key_name=$$ai_api_key" >> $(STAGING_CONFIG); \
	fi; \
	if [ -n "$$ai_url" ]; then \
		echo "AI_URL=$$ai_url" >> $(STAGING_CONFIG); \
	fi; \
	echo "" >> $(STAGING_CONFIG); \
	echo "# PostgreSQL" >> $(STAGING_CONFIG); \
	echo "POSTGRES_PASSWORD=postgres" >> $(STAGING_CONFIG); \
	echo "" >> $(STAGING_CONFIG); \
	echo "# Migration User" >> $(STAGING_CONFIG); \
	echo "DB_MIGRATION_USER=migration" >> $(STAGING_CONFIG); \
	echo "DB_MIGRATION_PASSWORD=migration" >> $(STAGING_CONFIG); \
	echo "" >> $(STAGING_CONFIG); \
	echo "# Application User" >> $(STAGING_CONFIG); \
	echo "DB_APP_USER=appuser" >> $(STAGING_CONFIG); \
	echo "DB_APP_PASSWORD=appuser" >> $(STAGING_CONFIG); \
	echo "" >> $(STAGING_CONFIG); \
	echo "# Keycloak Database User" >> $(STAGING_CONFIG); \
	echo "DB_KEYCLOAK_USER=keycloak" >> $(STAGING_CONFIG); \
	echo "DB_KEYCLOAK_PASSWORD=keycloak" >> $(STAGING_CONFIG); \
	echo "" >> $(STAGING_CONFIG); \
	echo "# Keycloak Admin" >> $(STAGING_CONFIG); \
	echo "KEYCLOAK_ADMIN=admin" >> $(STAGING_CONFIG); \
	echo "KEYCLOAK_ADMIN_PASSWORD=admin" >> $(STAGING_CONFIG); \
	echo "" >> $(STAGING_CONFIG); \
	echo "# Keycloak Test User" >> $(STAGING_CONFIG); \
	echo "KEYCLOAK_TEST_USER=testuser" >> $(STAGING_CONFIG); \
	echo "KEYCLOAK_TEST_PASSWORD=testuser" >> $(STAGING_CONFIG); \
	\
	echo ""; \
	echo "[OK] Staging config saved to $(STAGING_CONFIG)"

# ============================================================
# SETUP DEPLOY (PROD) - Cloud VM, manual credentials
# ============================================================
setup-deploy:
	@if [ -z "$(CLOUD_PROVIDER)" ] || [ -z "$(AI_PROVIDER)" ] || [ -z "$(POSTGRES_PASSWORD)" ]; then \
		echo "╔════════════════════════════════════════╗"; \
		echo "║      Production Setup (Cloud)          ║"; \
		echo "╚════════════════════════════════════════╝"; \
		echo ""; \
		if [ -z "$(CLOUD_PROVIDER)" ]; then \
			echo "┌─ Cloud Provider ─────────────────────────"; \
			echo "│  1) AWS"; \
			echo "│  2) GCP"; \
			echo "│  3) Azure"; \
			echo "└──────────────────────────────────────────"; \
			read -p "Enter choice [1-3]: " cloud_choice; \
			case $$cloud_choice in \
				1) provider="aws";; \
				2) provider="gcp";; \
				3) provider="azure";; \
				*) echo "[FAIL] Invalid choice"; exit 1;; \
			esac; \
		else \
			provider="$(CLOUD_PROVIDER)"; \
		fi; \
		echo ""; \
		if [ -z "$(AI_PROVIDER)" ]; then \
			echo "┌─ AI Provider ──────────────────────────────"; \
			echo "│  1) OpenAI"; \
			echo "│  2) Gemini (Google)"; \
			echo "│  3) Anthropic"; \
			echo "│  4) Mistral"; \
			echo "│  5) Ollama (local)"; \
			echo "│  6) LM Studio (local)"; \
			echo "└──────────────────────────────────────────"; \
			read -p "Enter choice [1-6]: " ai_choice; \
			case $$ai_choice in \
				1) ai_provider="openai"; ai_key_name="OPENAI_API_KEY";; \
				2) ai_provider="gemini"; ai_key_name="GOOGLE_API_KEY";; \
				3) ai_provider="anthropic"; ai_key_name="ANTHROPIC_API_KEY";; \
				4) ai_provider="mistral"; ai_key_name="MISTRAL_API_KEY";; \
				5) ai_provider="ollama"; ai_key_name="";; \
				6) ai_provider="lmstudio"; ai_key_name="";; \
				*) echo "[FAIL] Invalid choice"; exit 1;; \
			esac; \
			ai_api_key=""; \
			ai_url=""; \
			if [ -n "$$ai_key_name" ]; then \
				echo ""; \
				read -s -p "Enter $$ai_key_name: " ai_api_key; \
				echo ""; \
			else \
				if [ "$$ai_provider" = "ollama" ]; then \
					default_url="http://localhost:11434"; \
				else \
					default_url="http://localhost:1234"; \
				fi; \
				echo ""; \
				read -p "Enter $$ai_provider URL [$$default_url]: " ai_url; \
				ai_url=$${ai_url:-$$default_url}; \
			fi; \
		else \
			ai_provider="$(AI_PROVIDER)"; \
			ai_api_key="$(AI_API_KEY)"; \
			ai_url="$(AI_URL)"; \
			case $$ai_provider in \
				openai) ai_key_name="OPENAI_API_KEY";; \
				gemini) ai_key_name="GOOGLE_API_KEY";; \
				anthropic) ai_key_name="ANTHROPIC_API_KEY";; \
				mistral) ai_key_name="MISTRAL_API_KEY";; \
				ollama|lmstudio) ai_key_name="";; \
				*) echo "[FAIL] Invalid AI_PROVIDER: $$ai_provider"; exit 1;; \
			esac; \
			if [ -z "$$ai_key_name" ] && [ -z "$$ai_url" ]; then \
				if [ "$$ai_provider" = "ollama" ]; then \
					ai_url="http://localhost:11434"; \
				else \
					ai_url="http://localhost:1234"; \
				fi; \
			fi; \
		fi; \
		echo ""; \
		if [ -z "$(POSTGRES_PASSWORD)" ]; then \
			echo "┌─ Database Credentials (Production) ────────"; \
			echo "└──────────────────────────────────────────"; \
			echo ""; \
			echo "-- PostgreSQL Superuser --"; \
			read -s -p "postgres password: " pg_password; echo ""; \
			echo ""; \
			echo "-- Migration User --"; \
			read -p "migration username [migration]: " mig_user; \
			mig_user=$${mig_user:-migration}; \
			read -s -p "migration password: " mig_password; echo ""; \
			echo ""; \
			echo "-- Application User --"; \
			read -p "app username [appuser]: " app_user; \
			app_user=$${app_user:-appuser}; \
			read -s -p "app password: " app_password; echo ""; \
			echo ""; \
			echo "-- Keycloak Database User --"; \
			read -p "keycloak db username [keycloak]: " kc_db_user; \
			kc_db_user=$${kc_db_user:-keycloak}; \
			read -s -p "keycloak db password: " kc_db_password; echo ""; \
			echo ""; \
			echo "┌─ Keycloak Admin (Production) ──────────────"; \
			echo "└──────────────────────────────────────────"; \
			read -p "Keycloak admin username: " kc_admin; \
			read -s -p "Keycloak admin password: " kc_admin_password; echo ""; \
		else \
			pg_password="$(POSTGRES_PASSWORD)"; \
			mig_user="$(DB_MIGRATION_USER)"; \
			mig_password="$(DB_MIGRATION_PASSWORD)"; \
			app_user="$(DB_APP_USER)"; \
			app_password="$(DB_APP_PASSWORD)"; \
			kc_db_user="$(DB_KEYCLOAK_USER)"; \
			kc_db_password="$(DB_KEYCLOAK_PASSWORD)"; \
			kc_admin="$(KEYCLOAK_ADMIN)"; \
			kc_admin_password="$(KEYCLOAK_ADMIN_PASSWORD)"; \
		fi; \
	else \
		provider="$(CLOUD_PROVIDER)"; \
		ai_provider="$(AI_PROVIDER)"; \
		ai_api_key="$(AI_API_KEY)"; \
		ai_url="$(AI_URL)"; \
		pg_password="$(POSTGRES_PASSWORD)"; \
		mig_user="$(DB_MIGRATION_USER)"; \
		mig_password="$(DB_MIGRATION_PASSWORD)"; \
		app_user="$(DB_APP_USER)"; \
		app_password="$(DB_APP_PASSWORD)"; \
		kc_db_user="$(DB_KEYCLOAK_USER)"; \
		kc_db_password="$(DB_KEYCLOAK_PASSWORD)"; \
		kc_admin="$(KEYCLOAK_ADMIN)"; \
		kc_admin_password="$(KEYCLOAK_ADMIN_PASSWORD)"; \
		case $$ai_provider in \
			openai) ai_key_name="OPENAI_API_KEY";; \
			gemini) ai_key_name="GOOGLE_API_KEY";; \
			anthropic) ai_key_name="ANTHROPIC_API_KEY";; \
			mistral) ai_key_name="MISTRAL_API_KEY";; \
			ollama|lmstudio) ai_key_name="";; \
			*) echo "[FAIL] Invalid AI_PROVIDER: $$ai_provider"; exit 1;; \
		esac; \
		if [ -z "$$ai_key_name" ] && [ -z "$$ai_url" ]; then \
			if [ "$$ai_provider" = "ollama" ]; then \
				ai_url="http://localhost:11434"; \
			else \
				ai_url="http://localhost:1234"; \
			fi; \
		fi; \
	fi; \
	\
	echo "# Auto-generated by make setup-deploy" > $(DEPLOY_CONFIG); \
	echo "" >> $(DEPLOY_CONFIG); \
	echo "# Cloud & Environment" >> $(DEPLOY_CONFIG); \
	echo "CLOUD_PROVIDER=$$provider" >> $(DEPLOY_CONFIG); \
	echo "ENVIRONMENT=prod" >> $(DEPLOY_CONFIG); \
	echo "" >> $(DEPLOY_CONFIG); \
	echo "# AI Provider" >> $(DEPLOY_CONFIG); \
	echo "AI_PROVIDER=$$ai_provider" >> $(DEPLOY_CONFIG); \
	if [ -n "$$ai_key_name" ] && [ -n "$$ai_api_key" ]; then \
		echo "$$ai_key_name=$$ai_api_key" >> $(DEPLOY_CONFIG); \
	fi; \
	if [ -n "$$ai_url" ]; then \
		echo "AI_URL=$$ai_url" >> $(DEPLOY_CONFIG); \
	fi; \
	echo "" >> $(DEPLOY_CONFIG); \
	echo "# PostgreSQL" >> $(DEPLOY_CONFIG); \
	echo "POSTGRES_PASSWORD=$$pg_password" >> $(DEPLOY_CONFIG); \
	echo "" >> $(DEPLOY_CONFIG); \
	echo "# Migration User" >> $(DEPLOY_CONFIG); \
	echo "DB_MIGRATION_USER=$$mig_user" >> $(DEPLOY_CONFIG); \
	echo "DB_MIGRATION_PASSWORD=$$mig_password" >> $(DEPLOY_CONFIG); \
	echo "" >> $(DEPLOY_CONFIG); \
	echo "# Application User" >> $(DEPLOY_CONFIG); \
	echo "DB_APP_USER=$$app_user" >> $(DEPLOY_CONFIG); \
	echo "DB_APP_PASSWORD=$$app_password" >> $(DEPLOY_CONFIG); \
	echo "" >> $(DEPLOY_CONFIG); \
	echo "# Keycloak Database User" >> $(DEPLOY_CONFIG); \
	echo "DB_KEYCLOAK_USER=$$kc_db_user" >> $(DEPLOY_CONFIG); \
	echo "DB_KEYCLOAK_PASSWORD=$$kc_db_password" >> $(DEPLOY_CONFIG); \
	echo "" >> $(DEPLOY_CONFIG); \
	echo "# Keycloak Admin" >> $(DEPLOY_CONFIG); \
	echo "KEYCLOAK_ADMIN=$$kc_admin" >> $(DEPLOY_CONFIG); \
	echo "KEYCLOAK_ADMIN_PASSWORD=$$kc_admin_password" >> $(DEPLOY_CONFIG); \
	\
	echo ""; \
	echo "[OK] Production config saved to $(DEPLOY_CONFIG)"

# ============================================================
# TEST SETUP - Automated tests
# ============================================================
test-setup:
	@./scripts/test-setup.sh
